### Site info:
title: Yarn Then Blog
tagline: Just a blog to share my thoughts and ideas
author: Yarn Then Cohos King
email: yarnthen@gmail.com
description: "Freshman21 is a Jekyll blog theme." # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "Jekyll, theme, Freshman21"
baseurl: "/yarnthencohosking" # the subpath of your site, e.g. /blog/
url: "https://yarnthen.github.io" # the base hostname & protocol for your site
locale: en_US

### Personal info and site tools info:
disqus_shortname: yarnthen
favicon:     "/images/favicon.ico"
aboutme: Hi, I am Yarn Then Cohos King. Welcome to my blog. I have created a lot of small ultilites using Excel, Powershell, SharePoint to make my life and others better. Now I am sharing these as well as my thoughts and ideas to benefit others via this blog.  # these are shown on aboutme-sidebar.
aboutme_photo: "/images/yarnthen.png"
google_analytics_key: UA-104524488-1 # put YOUR key here to enable tracking! (blank to disable)
### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English (en), Chinese (cn), Japanese (jp), Polish (pl), Korean (kr), Russian (ru), and Turkish (tr)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "
      Google_search: "Site Search"
      Home: "Home"
      About: "About"
      Guestbook: "Guestbook"
      Subscribe: "Subscribe"

### your Blogroll info, only name can shown on the page.

Blogroll:
      - name: Freshman
        href: http://yulijia.net/freshman
        title: Another Jekyll blog theme
      - name: author's website
        href: http://yulijia.net/
        title: Lijia Yu's website


### Build settings
markdown: kramdown
#highlighter: pygments
kramdown:
        input: GFM
        syntax_highlighter: rouge
plugins: [jekyll-paginate, jekyll-sitemap, jekyll-seo-tag]
paginate: 5
excerpt_separator: <!-- more -->
